# Generated by Django 6.0.3 on 2026-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("counterparty", models.CharField(max_length=255)),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("OIL", "Crude Oil"),
                            ("GAS", "Natural Gas"),
                            ("POWER", "Electricity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=4, max_digits=15)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("BBL", "Barrels"),
                            ("MMBTU", "Million British Thermal Units"),
                            ("MWH", "Megawatt Hours"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CAPTURED", "Captured"),
                            ("CONFIRMED", "Confirmed"),
                            ("SETTLED", "Settled"),
                        ],
                        default="CAPTURED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
