# Generated by Django 6.0.3 on 2026-03-09 17:19

import trades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="id",
            field=models.IntegerField(
                default=trades.models.generate_trade_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
