# Generated by Django 6.0.3 on 2026-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_alter_trade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="accrual_amount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="actual_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="invoice_type",
            field=models.CharField(
                blank=True,
                choices=[("AP", "Accounts Payable"), ("AR", "Accounts Receivable")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="transport_mode",
            field=models.CharField(
                blank=True,
                choices=[("VESSEL", "Vessel"), ("TRAIN", "Train"), ("TRUCK", "Truck")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="vessel_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="status",
            field=models.CharField(
                choices=[
                    ("CAPTURED", "Captured"),
                    ("APPROVED", "Approved"),
                    ("SCHEDULED", "Scheduled"),
                    ("ACTUALIZED", "Actualized"),
                    ("INVOICED", "Invoiced"),
                ],
                default="CAPTURED",
                max_length=20,
            ),
        ),
    ]
